apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-geocoder
  labels:
    app: reverse-geocoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-geocoder
  template:
    metadata:
      labels:
        app: reverse-geocoder
    spec:
      # Prefer control-plane node but allow phone nodes
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
          - weight: 50
            preference:
              matchExpressions:
              - key: device-type
                operator: In
                values:
                - phone
      # Add tolerations for both control-plane and phone nodes
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      - key: node-role.kubernetes.io/phone
        effect: NoSchedule
      containers:
      - name: reverse-geocoder
        image: reverse-geocoder:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8090
          name: http
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 24  # 2 minutes total (24 * 5s)
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        env:
        - name: JAVA_OPTS
          value: "-Xmx1024m -Xms512m -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication"
